# Generated by Django 2.1.4 on 2019-01-13 15:20

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('is_live', models.BooleanField(default=False)),
                ('photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_latest', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=40)),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_latest', models.BooleanField(default=True)),
                ('post_type', models.CharField(choices=[('News', 'News'), ('Editorial', 'Editorial'), ('Opinion', 'Opinion'), ('Event', 'Event')], default='News', max_length=15)),
                ('post_title', models.CharField(max_length=100)),
                ('post_author', models.CharField(blank=True, max_length=40)),
                ('post_date', models.DateTimeField(blank=True, verbose_name='Posted Date')),
                ('post_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('content', ckeditor.fields.RichTextField()),
                ('event_date', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_latest', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=20)),
                ('video', models.URLField(verbose_name='Youtube Embed Url in src')),
            ],
        ),
    ]
