# Generated by Django 2.1.4 on 2019-01-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('image_1', models.ImageField(blank=True, upload_to='')),
                ('image_2', models.ImageField(blank=True, upload_to='')),
                ('image_3', models.ImageField(blank=True, upload_to='')),
                ('image_4', models.ImageField(blank=True, upload_to='')),
                ('is_latest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_type', models.CharField(choices=[('News', 'News'), ('Editorial', 'Editorial'), ('Opinion', 'Opinion'), ('Event', 'Event')], default='News', max_length=15)),
                ('post_title', models.CharField(max_length=100)),
                ('post_author', models.CharField(blank=True, max_length=40)),
                ('post_date', models.DateTimeField(auto_now=True, verbose_name='Posted Date')),
                ('post_keywords', models.TextField(blank=True)),
                ('post_photo_1', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('post_photo_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('post_photo_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('post_youtube_video_src', models.URLField(verbose_name='Youtube Embed Url in src')),
                ('text_content_1', models.TextField()),
                ('sub_heading_1', models.CharField(max_length=30)),
                ('text_content_2', models.TextField(blank=True)),
                ('sub_heading_2', models.CharField(blank=True, max_length=30)),
                ('text_content_3', models.TextField(blank=True)),
                ('event_date', models.CharField(blank=True, max_length=60)),
                ('is_latest', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('video', models.URLField(verbose_name='Youtube Embed Url in src')),
                ('is_latest', models.BooleanField(default=True)),
            ],
        ),
    ]
