# Generated by Django 2.1.4 on 2019-01-02 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190102_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_keywords',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
