# Generated by Django 2.1.4 on 2019-01-04 06:51

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20190102_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='event_date',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_keywords',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_photo_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_photo_3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_youtube_video_src',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_heading_1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_heading_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content_2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content_3',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(blank=True, verbose_name='Posted Date'),
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content_1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
