# Generated by Django 2.1.4 on 2019-01-04 07:06

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20190104_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content_2',
            field=tinymce.models.HTMLField(default='hello'),
            preserve_default=False,
        ),
    ]
