# Generated by Django 2.1.4 on 2019-01-04 07:20

import ckeditor.fields
from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20190104_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='text_content_2',
            field=tinymce.models.HTMLField(default='hello'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='text_content_1',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
