# Generated by Django 2.1.4 on 2019-01-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_auto_20190104_1820'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text_content_1',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='text_content_2',
        ),
    ]
