# Generated by Django 2.1.4 on 2019-01-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20190105_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='event_date',
            field=models.CharField(default='january', max_length=50),
            preserve_default=False,
        ),
    ]
