# Generated by Django 2.1.4 on 2019-01-04 21:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_event_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_live', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=50)),
                ('photo_1', models.ImageField(blank=True, upload_to='')),
                ('photo_2', models.ImageField(blank=True, upload_to='')),
                ('description', models.TextField()),
                ('contact_info', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
