# Generated by Django 2.1.4 on 2019-01-04 21:37

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_advert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='contact_info',
            field=tinymce.models.HTMLField(),
        ),
    ]
