# Generated by Django 2.1.4 on 2019-01-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_advert_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='contact_info',
            field=models.TextField(),
        ),
    ]
