# Generated by Django 2.1.4 on 2019-01-07 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20190105_1504'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='event_date',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
