# Generated by Django 2.1.4 on 2019-01-13 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20190107_1431'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advert',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='description',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='photo_2',
        ),
        migrations.RemoveField(
            model_name='advert',
            name='priority',
        ),
        migrations.AlterField(
            model_name='advert',
            name='title',
            field=models.CharField(max_length=20),
        ),
    ]
